apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>App 1</title>
    </head>
    <body>
      <h1>This is APP 1</h1>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1
spec:
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html-1

---
apiVersion: v1
kind: Service
metadata:
  name: app-1-lb
spec:
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP